name: Codecov
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Before Install
        run: |
          pip install requests
          chmod +x gradlew
          chmod +x gradle/wrapper/gradle-wrapper.jar
      - name: Run Tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
          EXPECTED_COVERAGE: ${{ secrets.EXPECTED_COVERAGE }}
        run: |
          ./gradlew build
          ./gradlew test
          bash <(curl -s https://codecov.io/bash)
          python request.py
      - name: Upstream to Standards
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COVERAGE_SOURCE_FILE: ${{ secrets.COVERAGE_SOURCE_FILE }}
        if: ${{ github.event_name == 'push'}}
        run: |
          wget --header "Authorization: token ${GH_TOKEN}" \
          --header "Accept: application/vnd.github.v3.raw" \
          https://api.github.com/repos/codecov/standards/contents/upstream.sh
          bash upstream.sh